// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Imageinfo is the predicate function for imageinfo builders.
type Imageinfo func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderItem is the predicate function for orderitem builders.
type OrderItem func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Siteui is the predicate function for siteui builders.
type Siteui func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
