version: "3.8"

volumes:
  sthl_volume:
  s3_volume:

services:
  accountdb:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - sthl_volume:/var/lib/postgresql/data

  localstack-s3:
    image: localstack/localstack
    container_name: localstack-s3
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
    environment:
      # - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EAGER_SERVICE_LOADING=1
      - SERVICES=s3
      - S3_DIR=/tmp/s3-buckets
      - S3_SKIP_KMS_KEY_VALIDATION=1
      - S3_SKIP_SIGNATURE_VALIDATION=1
    volumes:
      - s3_volume:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
