// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sthl/ent/order"
	"sthl/ent/orderitem"
	"sthl/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OrderItemUpdate is the builder for updating OrderItem entities.
type OrderItemUpdate struct {
	config
	hooks    []Hook
	mutation *OrderItemMutation
}

// Where appends a list predicates to the OrderItemUpdate builder.
func (oiu *OrderItemUpdate) Where(ps ...predicate.OrderItem) *OrderItemUpdate {
	oiu.mutation.Where(ps...)
	return oiu
}

// SetOrderID sets the "order_id" field.
func (oiu *OrderItemUpdate) SetOrderID(u uuid.UUID) *OrderItemUpdate {
	oiu.mutation.SetOrderID(u)
	return oiu
}

// SetProductID sets the "product_id" field.
func (oiu *OrderItemUpdate) SetProductID(u uuid.UUID) *OrderItemUpdate {
	oiu.mutation.SetProductID(u)
	return oiu
}

// SetPurchasedName sets the "purchased_name" field.
func (oiu *OrderItemUpdate) SetPurchasedName(s string) *OrderItemUpdate {
	oiu.mutation.SetPurchasedName(s)
	return oiu
}

// SetPurchasedPrice sets the "purchased_price" field.
func (oiu *OrderItemUpdate) SetPurchasedPrice(f float64) *OrderItemUpdate {
	oiu.mutation.ResetPurchasedPrice()
	oiu.mutation.SetPurchasedPrice(f)
	return oiu
}

// AddPurchasedPrice adds f to the "purchased_price" field.
func (oiu *OrderItemUpdate) AddPurchasedPrice(f float64) *OrderItemUpdate {
	oiu.mutation.AddPurchasedPrice(f)
	return oiu
}

// SetQuantity sets the "quantity" field.
func (oiu *OrderItemUpdate) SetQuantity(i int) *OrderItemUpdate {
	oiu.mutation.ResetQuantity()
	oiu.mutation.SetQuantity(i)
	return oiu
}

// AddQuantity adds i to the "quantity" field.
func (oiu *OrderItemUpdate) AddQuantity(i int) *OrderItemUpdate {
	oiu.mutation.AddQuantity(i)
	return oiu
}

// SetOwnerID sets the "owner" edge to the Order entity by ID.
func (oiu *OrderItemUpdate) SetOwnerID(id uuid.UUID) *OrderItemUpdate {
	oiu.mutation.SetOwnerID(id)
	return oiu
}

// SetOwner sets the "owner" edge to the Order entity.
func (oiu *OrderItemUpdate) SetOwner(o *Order) *OrderItemUpdate {
	return oiu.SetOwnerID(o.ID)
}

// Mutation returns the OrderItemMutation object of the builder.
func (oiu *OrderItemUpdate) Mutation() *OrderItemMutation {
	return oiu.mutation
}

// ClearOwner clears the "owner" edge to the Order entity.
func (oiu *OrderItemUpdate) ClearOwner() *OrderItemUpdate {
	oiu.mutation.ClearOwner()
	return oiu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (oiu *OrderItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, OrderItemMutation](ctx, oiu.sqlSave, oiu.mutation, oiu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (oiu *OrderItemUpdate) SaveX(ctx context.Context) int {
	affected, err := oiu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (oiu *OrderItemUpdate) Exec(ctx context.Context) error {
	_, err := oiu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oiu *OrderItemUpdate) ExecX(ctx context.Context) {
	if err := oiu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oiu *OrderItemUpdate) check() error {
	if v, ok := oiu.mutation.PurchasedName(); ok {
		if err := orderitem.PurchasedNameValidator(v); err != nil {
			return &ValidationError{Name: "purchased_name", err: fmt.Errorf(`ent: validator failed for field "OrderItem.purchased_name": %w`, err)}
		}
	}
	if v, ok := oiu.mutation.PurchasedPrice(); ok {
		if err := orderitem.PurchasedPriceValidator(v); err != nil {
			return &ValidationError{Name: "purchased_price", err: fmt.Errorf(`ent: validator failed for field "OrderItem.purchased_price": %w`, err)}
		}
	}
	if v, ok := oiu.mutation.Quantity(); ok {
		if err := orderitem.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "OrderItem.quantity": %w`, err)}
		}
	}
	if _, ok := oiu.mutation.OwnerID(); oiu.mutation.OwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "OrderItem.owner"`)
	}
	return nil
}

func (oiu *OrderItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := oiu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderitem.Table, orderitem.Columns, sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeUUID))
	if ps := oiu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := oiu.mutation.ProductID(); ok {
		_spec.SetField(orderitem.FieldProductID, field.TypeUUID, value)
	}
	if value, ok := oiu.mutation.PurchasedName(); ok {
		_spec.SetField(orderitem.FieldPurchasedName, field.TypeString, value)
	}
	if value, ok := oiu.mutation.PurchasedPrice(); ok {
		_spec.SetField(orderitem.FieldPurchasedPrice, field.TypeFloat64, value)
	}
	if value, ok := oiu.mutation.AddedPurchasedPrice(); ok {
		_spec.AddField(orderitem.FieldPurchasedPrice, field.TypeFloat64, value)
	}
	if value, ok := oiu.mutation.Quantity(); ok {
		_spec.SetField(orderitem.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := oiu.mutation.AddedQuantity(); ok {
		_spec.AddField(orderitem.FieldQuantity, field.TypeInt, value)
	}
	if oiu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitem.OwnerTable,
			Columns: []string{orderitem.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: order.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := oiu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitem.OwnerTable,
			Columns: []string{orderitem.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: order.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, oiu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	oiu.mutation.done = true
	return n, nil
}

// OrderItemUpdateOne is the builder for updating a single OrderItem entity.
type OrderItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderItemMutation
}

// SetOrderID sets the "order_id" field.
func (oiuo *OrderItemUpdateOne) SetOrderID(u uuid.UUID) *OrderItemUpdateOne {
	oiuo.mutation.SetOrderID(u)
	return oiuo
}

// SetProductID sets the "product_id" field.
func (oiuo *OrderItemUpdateOne) SetProductID(u uuid.UUID) *OrderItemUpdateOne {
	oiuo.mutation.SetProductID(u)
	return oiuo
}

// SetPurchasedName sets the "purchased_name" field.
func (oiuo *OrderItemUpdateOne) SetPurchasedName(s string) *OrderItemUpdateOne {
	oiuo.mutation.SetPurchasedName(s)
	return oiuo
}

// SetPurchasedPrice sets the "purchased_price" field.
func (oiuo *OrderItemUpdateOne) SetPurchasedPrice(f float64) *OrderItemUpdateOne {
	oiuo.mutation.ResetPurchasedPrice()
	oiuo.mutation.SetPurchasedPrice(f)
	return oiuo
}

// AddPurchasedPrice adds f to the "purchased_price" field.
func (oiuo *OrderItemUpdateOne) AddPurchasedPrice(f float64) *OrderItemUpdateOne {
	oiuo.mutation.AddPurchasedPrice(f)
	return oiuo
}

// SetQuantity sets the "quantity" field.
func (oiuo *OrderItemUpdateOne) SetQuantity(i int) *OrderItemUpdateOne {
	oiuo.mutation.ResetQuantity()
	oiuo.mutation.SetQuantity(i)
	return oiuo
}

// AddQuantity adds i to the "quantity" field.
func (oiuo *OrderItemUpdateOne) AddQuantity(i int) *OrderItemUpdateOne {
	oiuo.mutation.AddQuantity(i)
	return oiuo
}

// SetOwnerID sets the "owner" edge to the Order entity by ID.
func (oiuo *OrderItemUpdateOne) SetOwnerID(id uuid.UUID) *OrderItemUpdateOne {
	oiuo.mutation.SetOwnerID(id)
	return oiuo
}

// SetOwner sets the "owner" edge to the Order entity.
func (oiuo *OrderItemUpdateOne) SetOwner(o *Order) *OrderItemUpdateOne {
	return oiuo.SetOwnerID(o.ID)
}

// Mutation returns the OrderItemMutation object of the builder.
func (oiuo *OrderItemUpdateOne) Mutation() *OrderItemMutation {
	return oiuo.mutation
}

// ClearOwner clears the "owner" edge to the Order entity.
func (oiuo *OrderItemUpdateOne) ClearOwner() *OrderItemUpdateOne {
	oiuo.mutation.ClearOwner()
	return oiuo
}

// Where appends a list predicates to the OrderItemUpdate builder.
func (oiuo *OrderItemUpdateOne) Where(ps ...predicate.OrderItem) *OrderItemUpdateOne {
	oiuo.mutation.Where(ps...)
	return oiuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (oiuo *OrderItemUpdateOne) Select(field string, fields ...string) *OrderItemUpdateOne {
	oiuo.fields = append([]string{field}, fields...)
	return oiuo
}

// Save executes the query and returns the updated OrderItem entity.
func (oiuo *OrderItemUpdateOne) Save(ctx context.Context) (*OrderItem, error) {
	return withHooks[*OrderItem, OrderItemMutation](ctx, oiuo.sqlSave, oiuo.mutation, oiuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (oiuo *OrderItemUpdateOne) SaveX(ctx context.Context) *OrderItem {
	node, err := oiuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (oiuo *OrderItemUpdateOne) Exec(ctx context.Context) error {
	_, err := oiuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oiuo *OrderItemUpdateOne) ExecX(ctx context.Context) {
	if err := oiuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oiuo *OrderItemUpdateOne) check() error {
	if v, ok := oiuo.mutation.PurchasedName(); ok {
		if err := orderitem.PurchasedNameValidator(v); err != nil {
			return &ValidationError{Name: "purchased_name", err: fmt.Errorf(`ent: validator failed for field "OrderItem.purchased_name": %w`, err)}
		}
	}
	if v, ok := oiuo.mutation.PurchasedPrice(); ok {
		if err := orderitem.PurchasedPriceValidator(v); err != nil {
			return &ValidationError{Name: "purchased_price", err: fmt.Errorf(`ent: validator failed for field "OrderItem.purchased_price": %w`, err)}
		}
	}
	if v, ok := oiuo.mutation.Quantity(); ok {
		if err := orderitem.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "OrderItem.quantity": %w`, err)}
		}
	}
	if _, ok := oiuo.mutation.OwnerID(); oiuo.mutation.OwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "OrderItem.owner"`)
	}
	return nil
}

func (oiuo *OrderItemUpdateOne) sqlSave(ctx context.Context) (_node *OrderItem, err error) {
	if err := oiuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderitem.Table, orderitem.Columns, sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeUUID))
	id, ok := oiuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := oiuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderitem.FieldID)
		for _, f := range fields {
			if !orderitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := oiuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := oiuo.mutation.ProductID(); ok {
		_spec.SetField(orderitem.FieldProductID, field.TypeUUID, value)
	}
	if value, ok := oiuo.mutation.PurchasedName(); ok {
		_spec.SetField(orderitem.FieldPurchasedName, field.TypeString, value)
	}
	if value, ok := oiuo.mutation.PurchasedPrice(); ok {
		_spec.SetField(orderitem.FieldPurchasedPrice, field.TypeFloat64, value)
	}
	if value, ok := oiuo.mutation.AddedPurchasedPrice(); ok {
		_spec.AddField(orderitem.FieldPurchasedPrice, field.TypeFloat64, value)
	}
	if value, ok := oiuo.mutation.Quantity(); ok {
		_spec.SetField(orderitem.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := oiuo.mutation.AddedQuantity(); ok {
		_spec.AddField(orderitem.FieldQuantity, field.TypeInt, value)
	}
	if oiuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitem.OwnerTable,
			Columns: []string{orderitem.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: order.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := oiuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitem.OwnerTable,
			Columns: []string{orderitem.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: order.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrderItem{config: oiuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, oiuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	oiuo.mutation.done = true
	return _node, nil
}
