// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sthl/ent/predicate"
	"sthl/ent/siteui"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SiteuiDelete is the builder for deleting a Siteui entity.
type SiteuiDelete struct {
	config
	hooks    []Hook
	mutation *SiteuiMutation
}

// Where appends a list predicates to the SiteuiDelete builder.
func (sd *SiteuiDelete) Where(ps ...predicate.Siteui) *SiteuiDelete {
	sd.mutation.Where(ps...)
	return sd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sd *SiteuiDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, SiteuiMutation](ctx, sd.sqlExec, sd.mutation, sd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sd *SiteuiDelete) ExecX(ctx context.Context) int {
	n, err := sd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sd *SiteuiDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(siteui.Table, sqlgraph.NewFieldSpec(siteui.FieldID, field.TypeUUID))
	if ps := sd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sd.mutation.done = true
	return affected, err
}

// SiteuiDeleteOne is the builder for deleting a single Siteui entity.
type SiteuiDeleteOne struct {
	sd *SiteuiDelete
}

// Where appends a list predicates to the SiteuiDelete builder.
func (sdo *SiteuiDeleteOne) Where(ps ...predicate.Siteui) *SiteuiDeleteOne {
	sdo.sd.mutation.Where(ps...)
	return sdo
}

// Exec executes the deletion query.
func (sdo *SiteuiDeleteOne) Exec(ctx context.Context) error {
	n, err := sdo.sd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{siteui.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sdo *SiteuiDeleteOne) ExecX(ctx context.Context) {
	if err := sdo.Exec(ctx); err != nil {
		panic(err)
	}
}
